/* automatically generated by rust-bindgen 0.68.1 */

#[doc = " DisplayID v2 data structure."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct di_displayid2 {
    _unused: [u8; 0],
}
extern "C" {
    #[doc = " Get the DisplayID v2 revision."]
    pub fn di_displayid2_get_revision(displayid2: *const di_displayid2) -> ::std::os::raw::c_int;
}
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_EXTENSION : di_displayid2_product_primary_use_case = 0 ;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_TEST:
    di_displayid2_product_primary_use_case = 1;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_GENERIC:
    di_displayid2_product_primary_use_case = 2;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_TV:
    di_displayid2_product_primary_use_case = 3;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_DESKTOP_PRODUCTIVITY : di_displayid2_product_primary_use_case = 4 ;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_DESKTOP_GAMING : di_displayid2_product_primary_use_case = 5 ;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_PRESENTATION : di_displayid2_product_primary_use_case = 6 ;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_HMD_VR:
    di_displayid2_product_primary_use_case = 7;
pub const di_displayid2_product_primary_use_case_DI_DISPLAYID2_PRODUCT_PRIMARY_USE_CASE_HMD_AR:
    di_displayid2_product_primary_use_case = 8;
#[doc = " Product primary use case identifier, defined in table 2-3."]
pub type di_displayid2_product_primary_use_case = ::std::os::raw::c_uint;
extern "C" {
    #[doc = " Get the DisplayID v2 product primary use case."]
    pub fn di_displayid2_get_product_primary_use_case(
        displayid2: *const di_displayid2,
    ) -> di_displayid2_product_primary_use_case;
}
